name: Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Create env file"
        run: |
          echo "NODE_ENV=${{ secrets.NODE_ENV}}" >> .env
          echo "PORT=${{ secrets.PORT}}" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI}}" >> .env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY}}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET}}" >> .env
          echo "EMAIL_SERVICE=${{ secrets.EMAIL_SERVICE}}" >> .env
          echo "EMAIL_PORT${{ secrets.EMAIL_PORT}}" >> .env
          echo "EMAIL_USERNAME${{ secrets.EMAIL_USERNAME}}" >> .env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD}}" >> .env
          echo "EMAIL_FROM=${{ secrets.EMAIL_FROM}}" >> .env

      - name: Copy .env file to server using SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".env"
          target: /var/www/projects/grocery-max-server/

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/projects/grocery-max-server
            if [ -d "node_modules" ]; then
              git pull
              export NVM_DIR=~/.nvm
              source ~/.nvm/nvm.sh  
              npm install
              pm2 reload grocery-max-server 

            else
              git clone git@github.com:asifulhaque087/grocery-max-server.git ./
              export NVM_DIR=~/.nvm
              source ~/.nvm/nvm.sh  
              npm install
              pm2 start npm --name grocery-max-server -- run start -- -p 3001
              # pm2 save
            fi
